### ISSUE TITLE
scenic_intersection_sampler throws RuntimeError.

### ISSUE THREAD

**Issue by junjihashimoto** [BerkeleyLearnVerify/VerifAI#12]
I am trying to run "Fuzz testing using Scenic".
`scenic_intersection_sampler.py` throws following RuntimeError.

```
$ python3 -u "scenic_intersection_sampler.py"                                                                                      
Traceback (most recent call last):                                                                                                 
  File "scenic_intersection_sampler.py", line 7, in <module>                                                                       
    sampler = ScenicSampler.fromScenario(path_to_scenic_file)                                                                      
  File "/home/hashimoto/.local/lib/python3.6/site-packages/verifai/samplers/scenic_sampler.py", line 215, in fromScenario          
    scenario = scenic.scenarioFromFile(path)                                                                                       
  File "/home/hashimoto/.local/lib/python3.6/site-packages/scenic/syntax/translator.py", line 81, in scenarioFromFile              
    return scenarioFromStream(stream, filename=fullpath, path=path)                                                                
  File "/home/hashimoto/.local/lib/python3.6/site-packages/scenic/syntax/translator.py", line 89, in scenarioFromStream            
    return constructScenarioFrom(namespace)                                                                                        
  File "/home/hashimoto/.local/lib/python3.6/site-packages/scenic/syntax/translator.py", line 1121, in constructScenarioFrom       
    pruning.prune(scenario, verbosity=verbosity)                                                                                   
  File "/home/hashimoto/.local/lib/python3.6/site-packages/scenic/core/pruning.py", line 75, in prune                              
    pruneContainment(scenario, verbosity)                                                                                          
  File "/home/hashimoto/.local/lib/python3.6/site-packages/scenic/core/pruning.py", line 112, in pruneContainment                  
    orientation=base.orientation)                                                                                                  
  File "/home/hashimoto/.local/lib/python3.6/site-packages/scenic/core/regions.py", line 407, in __init__                          
    raise RuntimeError(f'tried to create PolygonalRegion from non-polygon {polygon}')                                              
RuntimeError: tried to create PolygonalRegion from non-polygon LINESTRING (-9.579316028408845 53.30945542330336, -9.454489317418432 29)                                                                                                                               

```

**Comment by northtiger** [comment]
Same issues...Have you solved this?

**Comment by junjihashimoto** [comment]
I have not solved it. I'm giving up.
