### ISSUE TITLE
Simple Example

### ISSUE THREAD

**Issue by TomyYamy** [BerkeleyLearnVerify/VerifAI#3]
I'm trying to apply VerifAI falsifier to my in-house supervisor python class in webots 2019.
It's not, VerifAI issue. but I'm facing a inter-process communication issue in my environment. Something like following.

```
Initialized sampler
Traceback (most recent call last):
  File "verifaiFalsifier.py", line 41, in <module>
    falsifier.run_falsifier()
  File "verifai\verifai\falsifier.py", line 99, in run_falsifier
    sample, rho = self.server.run_server()
  File "verifai\verifai\server.py", line 160, in run_server
    sample = self.get_sample()
  File "verifai\verifai\server.py", line 144, in get_sample
    return self.sampler.nextSample()
  File "verifai\verifai\samplers\feature_sampler.py", line 113, in nextSample
    domainPoint = self.domainSampler.nextSample()
  File "verifai\verifai\samplers\cross_entropy.py", line 34, in nextSample
    f_val = self.f(current_sample)
  File "verifai\verifai\server.py", line 153, in evaluate_sample
    simulation_data = self.receive()
  File "verifai\verifai\server.py", line 127, in receive
    simulation_data = self.decode(b"".join(data))
  File "verifai\verifai\server.py", line 138, in decode
    return dill.loads(data)
  File "C:\Users\<USER_NAME>\AppData\Local\Programs\Python\Python37\lib\site-packages\dill\_dill.py", lin
e 317, in loads
    return load(file, ignore)
  File "C:\Users\<USER_NAME>\AppData\Local\Programs\Python\Python37\lib\site-packages\dill\_dill.py", lin
e 305, in load
    obj = pik.load()
EOFError: Ran out of input
```

It is little bit difficult to debugging because it is a inter-process communication issue and webots does not support debugger.

I wonder if you could give us simpler examples than"cones_lanechange_supervisor/cones_lanechange_supervisor.py" in the future.
Current cones_lanechange_supervisor.py works on Python3.6 & Webots 2018 further more tensorflow is needed. So it little bit complicated and we can expect user fails to install that. (But it's good as integration test-case.) 
My intention is just making unit test-case for verifai.falsifier <-> Supervisor.
I think one of candidate is C:\Program Files\Webots\projects\languages\python\worlds\example.wbt
because it is in python. (Mainly webots examples are in C++ or C)

In specific this issue, I can try it with Python3.6 & Webots 2018 soon.

**Comment by TomyYamy** [comment]
I didn't find this error in cones_lanechange_falsifier.py on Python3.6 & Webots 2018 & windows 7.
(I mean sending sample from falsifier class to supervisor seems to succeed.)
However, I'm struggling tensorflow setting up on Windows and because of that the sample does not works completely.

It's not essential issue for me.
I'm thinking to make a falsifier example with  C:\Program Files\Webots\projects\languages\python\worlds\example.wbt on  Python3.6 & Webots 2018 & windows 7, then attempt to apply Python3.7 & Webots 2019 & windows 7.

I think I must not use Windows. every installation does not work well in windows....

**Comment by TomyYamy** [comment]
I have made a very simple example by using /user/local/Webots/projects/languages/python/worlds/example.wbt
at simpleExample branch.
I checked it on Python3.6 & Webots 2018 & ubuntu18.04

**Comment by TomyYamy** [comment]
I think now VerifAI has various examples and those are enough,
