### ISSUE TITLE
Lane keeping example seems not working for me

### ISSUE THREAD

**Issue by Yougmark** [BerkeleyLearnVerify/VerifAI#7]
I don't see any samples running in the lane-keeping example.  It quits immediately once I run the `lanekeeping_simluation.py`.

Here is my output:
In one terminal:
```
~/VerifAI/verifai/simulators/car_simulator$ python3 examples/lanekeeping_LQR/la
nekeeping_falsifier.py
Initialized sampler
Traceback (most recent call last):
  File "examples/lanekeeping_LQR/lanekeeping_falsifier.py", line 36, in <module>
    falsifier.run_falsifier()
  File "/home/yang/.local/lib/python3.6/site-packages/verifai/falsifier.py", line 99, in run_falsifier
    sample, rho = self.server.run_server()
  File "/home/yang/.local/lib/python3.6/site-packages/verifai/server.py", line 160, in run_server
    sample = self.get_sample()
  File "/home/yang/.local/lib/python3.6/site-packages/verifai/server.py", line 144, in get_sample
    return self.sampler.nextSample()
  File "/home/yang/.local/lib/python3.6/site-packages/verifai/samplers/feature_sampler.py", line 113, in
nextSample
    domainPoint = self.domainSampler.nextSample()
  File "/home/yang/.local/lib/python3.6/site-packages/verifai/samplers/cross_entropy.py", line 34, in nextSample
    f_val = self.f(current_sample)
  File "/home/yang/.local/lib/python3.6/site-packages/verifai/server.py", line 153, in evaluate_sample
    simulation_data = self.receive()
  File "/home/yang/.local/lib/python3.6/site-packages/verifai/server.py", line 127, in receive
    simulation_data = self.decode(b"".join(data))
  File "/home/yang/.local/lib/python3.6/site-packages/verifai/server.py", line 138, in decode
    return dill.loads(data)
  File "/home/yang/.local/lib/python3.6/site-packages/dill/_dill.py", line 275, in loads
    return load(file, ignore, **kwds)
  File "/home/yang/.local/lib/python3.6/site-packages/dill/_dill.py", line 270, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/home/yang/.local/lib/python3.6/site-packages/dill/_dill.py", line 472, in load
    obj = StockUnpickler.load(self)
EOFError: Ran out of input
```
Another terminal:
```
~/VerifAI/verifai/simulators/car_simulator$ python3 examples/lanekeeping_LQR/lanekeeping_simulation.py
/home/yang/VerifAI/verifai/simulators/car_simulator
StructPoint(init_conditions=StructPoint(cruising_speed=(13.111158070882212,), theta_init=(-0.42611828733739926,), x_init=(-0.1777949125423149,)))
No new sample received.
End of all simulations
```

Please let me know if any other information is needed to debug this issue.

Thanks!

**Comment by dfremont** [comment]
Hello Ming, apologies for missing this report until now! To help me try to reproduce this, what version of Python are you using?
